tapall rcmdnk/file

tap homebrew/core
tap homebrew/services

brew ansible
brew awscli
brew bash
brew bash-completion
brew docker
brew docker-compose
brew ffmpeg
brew fish
brew fzf
brew ghc
brew git
brew git-lfs
brew gnupg
brew htop
brew icdiff
brew imagemagick
brew m-cli
brew mailhog
brew neofetch
brew neovim
brew nmap
brew optipng
brew ossp-uuid
brew php
brew php@7.1
brew postgresql
brew python
brew ranger
brew reattach-to-user-namespace
brew sc-im
brew sqlite
brew stow
brew the_silver_searcher
brew tldr
brew tmux
brew tree
brew vim
brew wget
brew yarn

tap homebrew/cask

cask google-chrome
cask 1password
cask adobe-creative-cloud
cask android-studio
cask discord
cask firefox
cask gimp
cask hyperswitch
cask iterm2
cask karabiner-elements
cask keybase
cask musescore
cask pocket-casts
cask postico
cask postman
cask sequel-pro
cask slack
cask spectacle
cask spotify
cask sublime-text
cask tower
cask ngrok
cask telegram
cask transmission
cask vlc

# App Store applications
appstore 406056744 Evernote (7.9)
appstore 775737590 iA Writer (5.2.6)
appstore 823766827 OneDrive (19.012.0121)
appstore 425424353 The Unarchiver (4.1.0)
appstore 1278508951 Trello (2.10.8)
appstore 1147396723 WhatsApp (0.3.2277)
appstore 497799835 Xcode (10.1)
